### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by biswajitguha01** [Cinnamonsroll/expressbots#3]
how to post server count ???

**Comment by biswajitguha01** [comment]
`(node:13104) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at C:\Users\Administrator\Desktop\expressbots-main\src\server\routers\queue.js:22:26
    at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\route.js:137:13)
    at checkAuth (C:\Users\Administrator\Desktop\expressbots-main\src\server\index.js:90:37)
    at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\expressbots-main\node_modules\express\lib\router\layer.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Cinnamonsroll** [comment]
What code did you use?
